site_name: oep-api
site_url: https://github.com/in-RET/oep-api
site_author: in.RET

# Repository
repo_name: in-RET/oep-api
repo_url: https://github.com/in-RET/oep-api

plugins:
    - glightbox
markdown_extensions:
    - toc:
        permalink: true
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.highlight:
          anchor_linenums: true
          use_pygments: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
extra_javascript:
    - js/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
    - 'Home': index.md
    - 'Developer Doc Help': possibilities.md
    - 'About': about.md

theme:
    name: material
    icon:
        repo: fontawesome/brands/github
        admonition:
            <type>: material/alert-outline
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: pink
          accent: pink
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode


        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: pink
          accent: pink
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

    language: en
    features:
        - content.tabs.link
        - content.code.copy

extra:
    social:
        - icon: fontawesome/solid/envelope
          link: mailto:ensys@hs-nordhausen.de
    generator: true
copyright: Copyright &copy; 2025 Institut für regenerative Energietechnik
